branches:
  only:
  - master
language: python
python:
- 2.7
env:
  global:
  - secure: NQR2NJO5c8V0WtGFkTUl0XnbMsr12Bec07MqrjbsJIL1X4ZBpqYi2XT0WFFWP78q1r4iNfGzUv5J2Pnj/NlrSBfFGK7kxRn67Znvw2SZ/rbZf7zUyYxs+6tf++MsztvzxjnvMDAUkDffLY7Nl0OzfkLGFnpdRCYnnjslmxrfsFE=
before_install:
- sudo apt-get install pandoc
- git submodule update --init --recursive
install:
- pip install -r requirements.txt --use-mirrors
script:
- fab build
after_success: bash deploy.sh
notifications:
  email:
    on_success: always
    on_failure: always
